server:
#  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  profiles:
    active: dev
  application:
    name: service-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8